### ISSUE TITLE
exact version of python

### ISSUE THREAD

**Issue by island255** [SoftSec-KAIST/TikNib#1]
I have looked through the readme but didn't find the exact version of python that I should use.

Would you introduce the exact version of python? I have tried some, but it didn't work.

**Comment by 0xdkay** [comment]
I tested TikNib with Python 3.5.2.

If it is the issue in installing the packages with `pip` in the latest versions of Python, could you try to remove the package versions in `requirement.txt`?

Otherwise, could you paste the errors so that I can look into it?

**Comment by island255** [comment]
I have tried Python 3.5.2; it occurs the following errors:

`Could not find a version that satisfies the requirement capstone==4.0.0rc1 (from -r requirements.txt (line 2)) (from versions: 2.0, 2.1, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5rc2, 3.0.5, 3.0.5.post1, 4.0.0, 4.0.1, 4.0.2)
`
`No matching distribution found for capstone==4.0.0rc1 (from -r requirements.txt (line 2))
`

Removing package versions of the second line meet errors:

` Could not find a version that satisfies the requirement scikit_learn==0.23.2 (from -r requirements.txt (line 6)) (from versions: 0.9, 0.10, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.14, 0.14.1, 0.15.0b1, 0.15.0b2, 0.15.0, 0.15.1, 0.15.2, 0.16b1, 0.16.0, 0.16.1, 0.17b1, 0.17, 0.17.1, 0.18rc2, 0.18, 0.18.1, 0.18.2, 0.19b2, 0.19.0, 0.19.1, 0.19.2, 0.20rc1, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.20.4, 0.21rc2, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22rc2.post1, 0.22rc3, 0.22, 0.22.1, 0.22.2.post1)`
`No matching distribution found for scikit_learn==0.23.2 (from -r requirements.txt (line 6))
` 

Removing versions of all packages can install the packages successfully.

**Comment by 0xdkay** [comment]
Thanks for the checking. I'll look into it and make it solidly support the versions.

**Comment by 0xdkay** [comment]
For making the original `requirements.txt`, I ran `pipreqs` in the project root. However, it may have produced an incorrect one.

I fixed it and confirmed that it works with Python 3.8. Please check 200043a
