### ISSUE TITLE
Issue about source_list.txt and input_list_find.txt

### ISSUE THREAD

**Issue by xiaoguai0992** [SoftSec-KAIST/TikNib#3]
Hi,

I want to run example.sh on ase18 provided in BinKit. But I am confused by source_list.txt and input_list_find.txt in example folder.

I find that source_list.txt contains a path to a file. "/home/dongkwan/data/scripts/gnu_packages/findutils/findutils-4.6.0"
According to extract_functype.py, this file may include may paths of binaries. But I do not know how the file is organized. Is there any example?

For input_list_find.txt, I guess that I need to build a corresponding file "input_file_ase18.txt", and put all ABSOLUTE path of each binary in "ase18_debug". Is it right?

Thank you very much.

**Comment by 0xdkay** [comment]
Sorry for my late response.

> I find that source_list.txt contains a path to a file. "/home/dongkwan/data/scripts/gnu_packages/findutils/findutils-4.6.0"
According to extract_functype.py, this file may include may paths of binaries. But I do not know how the file is organized. Is there any example?

`source_list.txt` contains the paths of source directories. `findutils-4.6.0` is the project root of the 'findutils' source code. One example of such directories can be one of the gnu source packages that you downloaded using [BinKit](https://github.com/SoftSec-KAIST/BinKit).

> For input_list_find.txt, I guess that I need to build a corresponding file "input_file_ase18.txt", and put all ABSOLUTE path of each binary in "ase18_debug". Is it right?

You are correct! `input_*.txt` contains the paths of compiled binaries (not directories!).

All paths should be given as ABSOLUTE!

Thanks!

**Comment by xiaoguai0992** [comment]
Thanks a lot for your reply!
