### ISSUE TITLE
ida version

### ISSUE THREAD

**Issue by qinzhengze** [SoftSec-KAIST/TikNib#4]
hi，is your ida pro version for linux is crack version. the network don't have linux crack version for 6.95 and 7.5. only have 6.4 version.but it does not work. i don‘t know what to do.

**Comment by 0xdkay** [comment]
I am not sure if IDA Pro v6.4 supports all APIs used in TikNib. Please check the APIs of v6.4.
BTW, we use a valid license, not a cracked one.

**Comment by qinzhengze** [comment]
Can you provide the TikNib windows version? Many researchers use the win version of IDA pro.

**Comment by 0xdkay** [comment]
Thanks for your suggestion. I will check if I can make TikNIb work in Windows, but this may take some time.
